name: flutter_is_lock_screen
description: "Detects if device is in lock screen. Useful for determining whether app entered background due to locking screen or leaving app."
version: 3.0.0
repository: https://github.com/heartcoded-software/flutter_is_lock_screen

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: de.heartcoded.flutter_is_lock_screen
        pluginClass: FlutterIsLockScreenPlugin
      ios:
        pluginClass: FlutterIsLockScreenPlugin